package org.example;

import java.util.*;

public class Main {
    public static void main(String[] args) {

        MyArrayList<Integer> arrayList = new MyArrayList<Integer>();
        arrayList.add(12);
        arrayList.add(24);
        arrayList.add(36);
        arrayList.add(48);
        arrayList.add(60);
        System.out.println(arrayList.size());
        System.out.println(arrayList.get(0));
        System.out.println(arrayList.get(10));
        arrayList.remove(10);
        arrayList.remove(0);
        System.out.println(arrayList.get(0));
        arrayList.remove(3);
        System.out.println(arrayList.size());
        System.out.println(arrayList.get(2));
        arrayList.clear();
        System.out.println(arrayList.size());
        arrayList.add(72);
        arrayList.add(84);
        arrayList.add(96);
        System.out.println(arrayList.size());
        System.out.println(arrayList.get(1));
        arrayList.remove(1);
        System.out.println(arrayList.get(1));
        arrayList.clear();
        System.out.println(arrayList.size());

        MyLinkedList<Integer> linkedList = new MyLinkedList<Integer>();
        linkedList.add(12);
        linkedList.add(24);
        linkedList.add(36);
        linkedList.add(48);
        linkedList.add(60);
        System.out.println(linkedList.size());
        System.out.println(linkedList.get(0));
        System.out.println(linkedList.get(10));
        linkedList.remove(10);
        linkedList.remove(0);
        System.out.println(linkedList.get(0));
        linkedList.remove(3);
        System.out.println(linkedList.size());
        System.out.println(linkedList.get(2));
        linkedList.clear();
        System.out.println(linkedList.size());
        linkedList.add(72);
        linkedList.add(84);
        linkedList.add(96);
        System.out.println(linkedList.size());
        System.out.println(linkedList.get(1));
        linkedList.remove(1);
        System.out.println(linkedList.get(1));
        linkedList.clear();
        System.out.println(linkedList.size());

        MyQueue<Integer> queue = new MyQueue<Integer>();
        queue.add(12);
        queue.add(24);
        queue.add(36);
        queue.add(48);
        queue.add(60);
        System.out.println(queue.size());
        System.out.println(queue.peek());
        System.out.println(queue.poll());
        System.out.println(queue.poll());
        System.out.println(queue.size());
        System.out.println(queue.poll());
        queue.clear();
        System.out.println(queue.size());
        queue.add(72);
        queue.add(84);
        queue.add(96);
        System.out.println(queue.size());
        System.out.println(queue.peek());
        System.out.println(queue.poll());
        System.out.println(queue.poll());
        System.out.println(queue.poll());
        queue.add(108);
        System.out.println(queue.poll());
        queue.clear();
        System.out.println(queue.size());

        MyStack<Integer> stack = new MyStack<Integer>();
        stack.push(12);
        stack.push(24);
        stack.push(36);
        stack.push(48);
        stack.push(60);
        System.out.println(stack.size());
        System.out.println(stack.peek());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.size());
        System.out.println(stack.pop());
        stack.clear();
        System.out.println(stack.size());
        stack.push(72);
        stack.push(84);
        stack.push(96);
        System.out.println(stack.size());
        System.out.println(stack.peek());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        stack.push(108);
        System.out.println(stack.pop());
        stack.clear();
        System.out.println(stack.size());

        MyHashMap<String, Integer> hashMap = new MyHashMap<String, Integer>();
        hashMap.put("one", 12);
        hashMap.put("two", 24);
        hashMap.put("three", 36);
        hashMap.put("four", 48);
        hashMap.put("five", 60);
        System.out.println(hashMap.size());
        System.out.println(hashMap.get("one"));
        System.out.println(hashMap.get("five"));
        System.out.println(hashMap.get("three"));
        hashMap.remove("one");
        System.out.println(hashMap.size());
        System.out.println(hashMap.get("four"));
        hashMap.clear();
        System.out.println(hashMap.size());
        hashMap.put("one", 72);
        hashMap.put("two", 84);
        hashMap.put("three", 96);
        System.out.println(hashMap.size());
        System.out.println(hashMap.get("one"));
        System.out.println(hashMap.get("two"));
        System.out.println(hashMap.get("three"));
        hashMap.remove("two");
        hashMap.put("three" , 108);
        System.out.println(hashMap.get("three"));
        hashMap.clear();
        System.out.println(hashMap.size());
    }
}